### ISSUE TITLE
Error: Unsupported sequence file

### ISSUE THREAD

**Issue by paigemaroni** [Taming-the-BEAST/Introduction-to-BEAST2#3]
Hi there BEAST2 team, 

I am attempting to work through your tutorial, "Practical: Running a simple analysis with BEAST2" however when I attempt to load in my NEXUS alignment (just a very small sub-set of my data), I receive the error warning "Error: Unsupported sequence file". Can you please tell me what I am doing wrong here? I am exporting the document from Geneious Prime. An example of my dataset is below. 

Any help would be greatly appreciated as I plan on using BEAST frequently in the near future. 
Thank you so much!

#NEXUS

BEGIN CHARACTERS;
	DIMENSIONS nchar=645;
	FORMAT datatype=dna gap=-;
	MATRIX
	AP004443	CTAGTATTTGGTGCTTGAGCTGGGATAGTGGGGACAGGCCTAAGCCTTTTAATTCGGGCCGAACTAAGCCAACCCGGGGCCCTCTTGGGCGACGACCAAATTTATAATGTAATTGTTACAGCACATGCCTTCGTGATAATTTTCTTTATAGTAATACCAATCATAATTGGAGGCTTCGGAAACTGACTCATCCCCCTTATGATCGGCGCCCCCGATATAGCATTCCCTCGGATAAACAACATGAGCTTTTGACTTCTCCCCCCTTCTTTCCTGTTACTTCTTGCCTCTTCAGGCGTCGAAGCAGGGGCCGGGACCGGATGAACCGTCTACCCCCCTCTAGCAGGCAACCTGGCACACGCCGGAGCCTCTGTTGACTTAACAATCTTTTCCTTACATCTAGCAGGGATCTCTTCAATCCTCGGGGCAATTAATTTCATCACAACCATCATCAACATAAAGCCCCCTGCTATATCTCAATACCAAACCCCCCTTTTCGTGTGATCCGTACTCATTACTGCCGTTCTTCTCCTTCTCTCCCTCCCCGTGCTTGCTGCCGGCATCACAATGCTCTTAACAGACCGCAATCTTAACACTACCTTCTTTGACCCAGCAGGAGGCGGAGACCCCATTCTCTACCAACACCTC
	AM498312	CTAGTATTTGGTGCTTGAGCTGGAATGGTCGGGACAGGCCTGAGCTTATTAATTCGGGCCGAACTAAGCCAACCCGGAGCCCTTTTAGGCGACGACCAAATCTACAACGTAATTGTTACAGCACATGCTTTCGTAATAATTTTCTTTATGGTAATACCAATTATAATTGGAGGTTTCGGGAATTGACTCATCCCCTTAATGATCGGGGCCCCCGATATAGCCTTTCCTCGAATAAATAACATAAGTTTTTGACTTCTCCCTCCCTCTTTCTTACTCCTCCTTGCCTCTTCTGGTGTAGAAGCGGGAGCCGGGACCGGATGAACTGTTTATCCCCCTCTTGCTGGTAATTTGGCCCACGCCGGAGCTTCTGTTGACCTAACAATTTTCTCATTACATTTAGCAGGAATTTCTTCAATTCTTGGGGCAATTAATTTTATTACAACCATTATCAACATAAAACCCCCTGCTATATCTCAGTACCAGACCCCTCTTTTCGTTTGATCTGTGCTCATTACAGCCGTACTTCTCCTCCTCTCTCTTCCTGTTCTTGCTGCCGGCATCACCATGCTTCTCACGGACCGAAATCTTAACACAACCTTCTTTGATCCTGCAGGAGGAGGAGACCCAATTCTTTATCAACACCTC
	KJ204977	CTAGTATTTGGTGCTTGAGCTGGAATGGTCGGGACAGGCCTGAGCTTATTAATTCGGGCCGAACTTAGCCAACCCGGAGCCCTTTTAGGTGACGACCAAATCTACAACGTAATTGTTACAGCGCATGCTTTCGTAATAATTTTCTTTATGGTAATACCAATTATAATTGGAGGTTTTGGGAATTGACTCATCCCCTTAATGATCGGGGCCCCCGATATAGCCTTTCCTCGAATAAATAATATAAGTTTTTGACTCTTACCACCCTCTTTCTTACTCCTTCTTGCCTCTTCTGGCGTAGAAGCGGGGGCCGGAACCGGGTGAACTGTTTACCCCCCTCTTGCTGGTAATTTAGCCCATGCTGGAGCCTCTGTAGACCTGACAATTTTCTCGCTACATTTAGCAGGGATTTCTTCAATTCTTGGGGCCATTAATTTTATTACAACCATCATCAACATGAAACCCCCTGCTATGTCTCAGTACCAAACCCCTCTTTTCGTTTGATCTGTTCTTATTACAGCCGTACTTCTCCTCCTCTCTCTCCCAGTCCTTGCTGCCGGCATCACCATGCTCCTGACAGACCGAAATCTTAATACAACCTTCTTTGATCCTGCAGGAGGGGGAGACCCAATTCTTTATCAACACCTC
	KJ128532	CTAGTATTTGGTGCTTGAGCTGGAATGGTCGGGACAGGCCTGAGCTTACTAATTCGGGCCGAACTTAGCCAACCCGGAGCCCTTTTAGGCGACGACCAGATTTACAACGTAATTGTTACAGCACATGCTTTCGTAATAATTTTCTTTATGGTAATACCAATTATAATTGGAGGTTTCGGGAATTGACTCATCCCCTTAATGATTGGGGCTCCCGATATAGCTTTCCCTCGAATAAATAATATAAGTTTTTGACTTCTACCACCCTCTTTCTTACTCCTTCTTGCCTCTTCTGGCGTAGAGGCGGGGGCCGGGACTGGATGAACTGTTTACCCCCCTCTCGCTGGCAATTTAGCCCATGCCGGGGCCTCTGTAGATCTAACAATTTTTTCACTACATTTAGCAGGGATTTCTTCAATTCTTGGGGCCATTAATTTTATTACAACCATTATTAATATGAAACCCCCTGCTATATCTCAATACCAAACCCCTCTTTTCGTTTGATCTGTACTTATCACAGCCGTACTTCTCCTCCTCTCTCTTCCTGTCCTTGCTGCCGGTATCACCATACTTCTAACCGACCGGAATCTTAACACAACCTTCTTTGACCCAGCAGGAGGAGGAGACCCAATTCTTTACCAACACCTC
KY659182	CTAGTATTTGGTGCTTGAGCTGGGATGGTGGGAACAGGCCTGAGTTTATTAATTCGAGCCGAACTTAGCCAACCCGGAGCCCTTTTAGGCGACGATCAAATTTACAACGTAATTGTCACAGCACATGCCTTCGTAATAATTTTCTTTATAGTAATACCAATTATAATCGGAGGTTTCGGAAATTGACTCGTCCCCCTAATGATTGGTGCCCCTGATATAGCCTTTCCTCGAATAAATAATATAAGCTTTTGGCTTCTTCCACCCTCTTTCTTACTCCTTCTTGCCTCTTCTGGTGTAGAAGCAGGGGCCGGAACCGGGTGAACCGTCTACCCTCCCCTTGCTGGTAATTTAGCCCATGCTGGAGCTTCTGTAGACCTAACAATTTTTTCTCTACATTTAGCAGGAATCTCTTCAATTCTTGGGGCAATTAATTTTATTACAACCATCATCAACATGAAACCCCCTGCTATATCTCAATATCAGACCCCTCTTTTCGTATGGTCCCTACTCATTACCGCCGTACTTCTCCTTCTCTCTCTCCCCGTCCTTGCTGCCGGCATCACCATGCTTCTAACAGATCGTAACCTTAACACAACATTCTTTGACCCCGCAGGGGGCGGAGACCCAATTCTCTACCAACACCTT
;
END;

**Comment by laduplessis** [comment]
Hi Paige, your NEXUS file is valid and I can load it in BEAUti 2.6.7. BEAUti looks at the file extension to figure out how to load it, so be sure to save your file with the extension .nex or .nexus or else BEAUti will throw the error you mentioned.
